framework:
    messenger:
        transports:
            # Uncomment the following line to enable a transport named "amqp"
            # amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': amqp

        default_bus: messenger.bus.commands

        buses:
            messenger.bus.commands:
                middleware:
                    - validation
                    # Ensures the handler & doctrine transaction is successful
                    # before dispatching sub-messages in a transaction (i.e events):
                    # - transaction
                    # - doctrine_transaction
            messenger.bus.queries: ~
